# Generated by Django 4.2.1 on 2023-05-04 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('src', models.GenericIPAddressField()),
                ('srcp', models.PositiveIntegerField(null=True)),
                ('dst', models.GenericIPAddressField()),
                ('dstp', models.PositiveIntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitorweb.agent')),
            ],
        ),
    ]
