# Generated by Django 4.2.2 on 2023-06-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('health', models.URLField()),
                ('status', models.CharField(max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_id', models.CharField(max_length=200, null=True)),
                ('rule_class', models.CharField(max_length=300)),
                ('filter_field', models.CharField(choices=[('URL', 'Request (URL)'), ('Status', 'Status code'), ('BBS', 'Body bytes sent'), ('User', 'Remote user'), ('ReqTime', 'Request time'), ('Body', 'Request body'), ('Header', 'Request headers')], max_length=30)),
                ('regex', models.CharField(max_length=1500, null=True)),
                ('deny', models.BooleanField(default=True)),
                ('ref', models.URLField(max_length=500, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_user', models.CharField(max_length=200)),
                ('status', models.PositiveIntegerField()),
                ('body_bytes_sent', models.PositiveIntegerField()),
                ('request_time', models.FloatField()),
                ('request', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('headers', models.CharField(max_length=1500)),
                ('remote_addr', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitorweb.agent')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitorweb.rule')),
            ],
        ),
    ]
