# Generated by Django 4.2.2 on 2023-06-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='filter_field',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='regex',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='rule_id',
        ),
        migrations.CreateModel(
            name='RuleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_field', models.CharField(choices=[('URL', 'Request (URL)'), ('Status', 'Status code'), ('BBS', 'Body bytes sent'), ('User', 'Remote user'), ('ReqTime', 'Request time'), ('Body', 'Request body'), ('Header', 'Request headers')], max_length=30)),
                ('regex', models.CharField(max_length=1500, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorweb.rule')),
            ],
        ),
    ]
