# Generated by Django 4.2.2 on 2023-06-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0002_remove_rule_filter_field_remove_rule_regex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='operator',
            field=models.CharField(choices=[('AND', 'AND (&&)'), ('OR', 'OR (||)')], default='OR', max_length=10),
        ),
        migrations.AlterField(
            model_name='rulecomponent',
            name='filter_field',
            field=models.CharField(choices=[('URL', 'Request (URL)'), ('Status', 'Status code'), ('BBS', 'Body bytes sent'), ('User', 'Remote user'), ('ReqTime', 'Request time'), ('Body', 'Request body'), ('Header', 'Request headers')], default='URL', max_length=30),
        ),
    ]
