# Generated by Django 4.2.2 on 2023-06-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0002_alert_isread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='isRead',
            new_name='isProcessed',
        ),
    ]
