# Generated by Django 4.2.2 on 2023-06-08 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitorweb', '0003_rename_isread_alert_isprocessed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='isProcessed',
            new_name='is_processed',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='deny',
            new_name='is_denied',
        ),
        migrations.AddField(
            model_name='alert',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
