# Generated by Django 4.2.2 on 2023-06-06 08:46

from django.db import migrations, models
import monitorweb.utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0004_alter_rule_operator_alter_rulecomponent_filter_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulecomponent',
            name='filter_field',
            field=models.CharField(choices=[(monitorweb.utils.enums.Request['url'], 'Request (URL)'), (monitorweb.utils.enums.Request['status'], 'Status code'), (monitorweb.utils.enums.Request['bbs'], 'Body bytes sent'), (monitorweb.utils.enums.Request['user'], 'Remote user'), (monitorweb.utils.enums.Request['req_time'], 'Request time'), (monitorweb.utils.enums.Request['body'], 'Request body'), (monitorweb.utils.enums.Request['headers'], 'Request headers'), (monitorweb.utils.enums.Request['ip'], 'Source IP address')], default='URL', max_length=30),
        ),
    ]
