# Generated by Django 4.2.2 on 2023-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0004_rename_isprocessed_alert_is_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
