# Generated by Django 4.2.2 on 2023-06-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0005_alter_rulecomponent_filter_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='body',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='alert',
            name='headers',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='alert',
            name='remote_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
