# Generated by Django 4.2.2 on 2023-06-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0006_alter_alert_processed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='health',
            field=models.URLField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(default='Registered', max_length=20),
        ),
    ]
