# Generated by Django 4.2.1 on 2023-06-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0007_alter_agent_health_alter_agent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IptablesRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('srcip', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=10)),
                ('chain', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('dport', models.PositiveIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitorweb.agent')),
            ],
        ),
    ]
