# Generated by Django 4.2.1 on 2023-06-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0008_iptablesrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptablesrule',
            name='action',
        ),
    ]
