# Generated by Django 4.2.1 on 2023-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0009_remove_iptablesrule_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='request',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rulecomponent',
            name='regex',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
