# Generated by Django 4.2.1 on 2023-07-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0010_alter_alert_request_alter_rulecomponent_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptablesrule',
            name='options',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
