# Generated by Django 4.2.1 on 2023-07-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0012_alter_iptablesrule_srcip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptablesrule',
            name='name',
            field=models.CharField(default='IptRule', max_length=200),
            preserve_default=False,
        ),
    ]
