# Generated by Django 4.2.1 on 2023-07-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorweb', '0013_alter_iptablesrule_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iptablesrule',
            unique_together={('srcip', 'protocol', 'chain', 'target', 'dport', 'options', 'agent')},
        ),
    ]
