# This is a newly created gmail account, only for testing purpose in this project, please do not use this account for any other purposes.

user:
  email: l30th3s3c0nd@gmail.com
  password: zodqvehylcctplgf